version: '2'

services:

    db:
        image: mysql
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: db
        ports:
            - "8866:80"
            
    phpapp:
        build: docker-sfapp
        entrypoint: bin/console server:run 0.0.0.0:8000
        ports:
            - 8877:8000
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            
    mailcatcher:
        image: schickling/mailcatcher
        ports:
            - "8879:1080"