imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@AcmeBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    app.path.livre_couvertures: /uploads/couvertures

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    serializer: { enabled: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'foundation_5_layout.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.project_dir%/var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    port: '%mailer_port%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

stof_doctrine_extensions:
    default_locale: '%locale%'
    orm:
        default:
            sluggable: true

liip_imagine: # http://symfony.com/doc/current/bundles/LiipImagineBundle/configuration.html
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~

        livre_listing:
            #default_image: '%kernel.project_dir%/web/images/default_livre.jpg'
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
                background: { size: [124, 94], position: center, color: '#000000' }
        
        livre_page_detail:
            #default_image: '%kernel.project_dir%/web/images/default_livre.jpg'
            quality: 75
            filters:
                thumbnail: { size: [360, 270], mode: outbound }

knp_paginator:
    template:
        pagination: 'default/pagination.html.twig'
        
easy_admin:
    site_name: 'Admin'
    entities:
        Livre:
            class: AppBundle\Entity\Livre
            form:
                fields:
                    - 'titre'
                    - 'description'
                    - { property: 'couvertureFile', type: 'vich_image' }
                    - { property: 'critiques', type: 'collection', type_options: { entry_type: 'AppBundle\Form\CritiqueType', by_reference: false } }
            list:
                fields:
                    - 'titre'
                    - { property: 'couverture', type: 'image', base_path: '%app.path.livre_couvertures%' }
                    - 'critiques'
                    - { property: 'description', template: 'description-dans-liste.html.twig' }

vich_uploader:
    db_driver: orm
    mappings:
        livre_image:
            uri_prefix:         '%app.path.livre_couvertures%'
            upload_destination: '%kernel.root_dir%/../web/uploads/couvertures'
            namer: vich_uploader.namer_uniqid