acme:
    resource: "@AcmeBundle/Controller/"
    type:     annotation
    prefix:   /acme

app:
    resource: '@AppBundle/Controller/'
    type: annotation

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"
    
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin